pulp/pulpcore-selinux

- README.md
- pulpcore.te
Changed building and installing steps in README:
- Pulp_port module has to be installed first, except for Fedora 31 and Fedora Rawhide in which pulp_port type is included in the base SELinux policy.
- The SELinux policy for Pulp was this way successfully installed on Fedora 30, Fedora 31, Fedora Rawhide, RHEL 7.5, RHEL 7.8, RHEL 8.0, RHEL 8.1 and RHEL 8.2 Beta.
Update pulpcore.te file:
- miscfiles_read_certs() replaced by miscfiles_read_generic_certs(), because miscfiles_read_certs() has been deprecated.
Fixed: https://pulp.plan.io/issues/6048
> Update README and pulpcore.te

- pulpcore.fc
This avoids having a conflict with the pulp-server 2.y.z SELinux policy which states:
/var/lib/pulp(/.*)? gen_context(system_u:object_r:httpd_sys_rw_content_t,s0)
re: #5995
https://pulp.plan.io/issues/5995
> Lists all directories inside /var/lib/pulp/ that are used by pulpcore

- README.md
- pulpcore.fc
- pulpcore.if
- pulpcore.te
- pulpcore_rhsmcertd.te
- pulpcore_semanage_port.txt
Support for RHEL 8.
Support for ansible.
Different types for client and server domains, together with separate
private types for /run, /tmp, /var/lib.
Support for multiple paths for the same executable.
> Major updates to the pulpcore policy

- pulpcore.te
- pulpcore_port.te
- pulpcore_rhsmcertd.te
Solution: Bump the version in the policies from 1.0 / 1.0.0
to 1.1.1, the next release.
fixes: #7617
https://pulp.plan.io/issues/7617
pulpcore-selinux version disagrees with tag
> pulpcore-selinux version disagrees with tag

- .github/workflows/tests.yml
While Github Actions can't load the actual policies, it can at least be built which provides some base guarantees.
> Add Github Actions

- pulpcore.fc
Since the locations of gunicorn and rq can differ, this starts to promote wrappers in libexec. This is also needed for RPM packaging where the files are in /usr/bin using the system wide interpreter. Other tools may be using those same files.
This is a draft so I can refer to it in my patches. It is ready for feedback, but I haven't tested this yet.
Open question: should the old bins be removed and only libexec?
> Use libexec wrappers

- pulpcore.fc
Since cc53e5c1ae8b87d0fb449dd8c42e8dc2841730bb the proper way to use gunicorn and rq is via /usr/libexec/pulpcore. This also matches the pulpcore-selinux package which only relabels python3-pulpcore.
Both installers have been modified so /usr/bin/{rq,gunicorn} can be dropped.
System packages should not touch anything in /usr/local so the paths should also be dropped. If anyone wants to depart from system packages and install to /usr/local, it's up to them to properly label paths. They can also place wrappers in `/usr/libexec/pulpcore`.
> Drop old gunicorn and rq paths

- pulpcore.fc
- pulpcore.if
- pulpcore.te
In the runtime directory, file transition was defined for plain files
and directories. With this update, also socket files are a subject of
the same transition.
> Set the correct SELinux type also for runtime socket files

- pulpcore.fc
Current label applied to /var/lib/pulp seems incosistent/erroneous
```
[root@localhost vagrant]# ls -lZ /var/lib | grep pulp
drwx-----x. pulp pulp unconfined_u:object_r:var_lib_t:s0 pulp
[root@localhost vagrant]# ls -lZ /var/lib/pulp/
drwxr-xr-x. pulp pulp unconfined_u:object_r:pulpcore_var_lib_t:s0 assets
drwxr-xr-x. pulp pulp unconfined_u:object_r:var_lib_t:s0 pulpcore_static
drwxrwxr-x. pulp pulp unconfined_u:object_r:pulpcore_var_lib_t:s0 tmp
```
Not how /var/lib/pulp and /var/lib/pulp/puplcore_static are wrongly
labelled. A restorecon didn't/wouldn't help as they are not part of the
fc file.
> pulpcore_var_lib_t: Label all the things under /var/lib/pulp

- README.md
- RELEASING.md
- pulpcore.te
- pulpcore_port.te
- pulpcore_rhsmcertd.te
I deleted the 1.2.1 release, but left the tag there.
The problem with it is that I forgot to bump the version string.
when I release 1.2.2, I'll do the changelog since 1.2.0.
> Release 1.2.2

- pulpcore.te
When the pulpcore resource worker runs galaxy-importer, tar is executed
to extract files from the specified archive. Symbolic links can be
present in the tarball, so the process needs the manage permissions.
> Allow pulpcore manage symlinks in /var/lib/pulp

- pulpcore.fc
- pulpcore.te
When Type=notify is used, it will open a unix socket (typically /run/systemd/notify). Prior to this, it was rejected. The result was that the service never really started and systemd ended up killing the service after some time.
Currently untested, hence a draft. Pushing it here for collaboration.
> Allow systemd Type=notify and label /run/pulpcore-(api|content).sock

- pulpcore.te
- pulpcore_port.te
- pulpcore_rhsmcertd.te
fixes: #9272
pulpcore-selinux needs SELinux changes for systemd Type=notify
https://pulp.plan.io/issues/9272
https://bugzilla.redhat.com/show_bug.cgi?id=1976783#
https://community.theforeman.org/t/katello-pulpcore-selinux-issues/24507
related to: #9271
gunicorn processes should be managed by systemd as Type=notify
https://pulp.plan.io/issues/9271
> Update for systemd type=notify, /etc/apache/ access, and release 1.2.5

- pulpcore.te
- pulpcore_port.te
- pulpcore_rhsmcertd.te
1.2.6 changelog
* Update comments for the systemd Type=notify support
* Add support for pulp-2to3-migration plugin
More info on pulp-2to3-migration plugin support:
I've tested this on an EL7 foreman machine with data, with and
without the policy changes.
Every added policy line was tested. (A corresponding alert happened
without the policy changes, but no alert hapepend with the policy
changes.)
fixes: #9468
As a pulp-2to3-migration user, I can run the migration with SELinux enabled
@mikedep333
> Migration plugin support & Release 1.2.6

- pulpcore.te
for the worker process.
fixes: #54
> Allow API/Content to read the kernel keyring

- pulpcore.te
kernel keyring for the API/content processes.
fixes: #66
> Fix pulpcore-worker being unable to read the

- pulpcore.fc
This wasn't done in the past to coexist with pulp-selinux (from Pulp 2), but those days are long gone. This also makes it easy to set the correct label on /var/lib/pulp/exports (as Katello does).
I think this addresses https://bugzilla.redhat.com/show_bug.cgi?id=2172833
> Set file contexts for all of /var/lib/pulp

- pulpcore.te
- pulpcore_port.te
- pulpcore_rhsmcertd.te
CHANGELOG:
* Set file contexts for all of /var/lib/pulp
* Note: The above removes the ability to exist alongside Pulp 2.
> Release 2.0.0

- pulpcore.fc
since pulpcore 3.33 there are new binaries to start pulpcore services, but those binaries were not properly labeled with pulpcore_server_exec_t like their old counterpart gunicorn
without that label, the services run as unconfined_service_t, which results in errors like httpd not being able to connect to them
while at it, also properly label the pulpcore-worker binary in /usr/bin
> correctly label pulpcore-(api|content) binaries

- staging_docs/admin/guides/extend-support.md
- staging_docs/admin/index.md
- staging_docs/dev/guides/release.md
> Migrate docs to new stack

- pulpcore.te
The old policy for this allowed access to files owned by Apache. This is no longer needed, nor is it needed to connect to MongoDB anymore.
> Drop pulp-2to3 migration support

- RELEASING.md
release notes feature.
We have to update RELEASING.md anyway because master -> main branch
change.
Tell me what you think of the format:
https://github.com/pulp/pulpcore-selinux/releases/tag/1.2.8
I personally don't like listing all the contributors for each commit (team effort vs individual effort), but community contributors might like being listed.
> Update RELEASING.md to use the Auto-generate

- pulpcore.fc
Apply the similar labels to venv installed pulp binaries as those directly in /usr/bin/.
Basically f57c41f32cc9ff8e34120bd3807805002256db23 with venv path.
> Correctly label pulpcore-(api|content) binaries in a venv

- .github/workflows/tests.yml
Both CentOS 7 and 8 are EOL and no longer available on the mirrors. Foreman has also dropped EL8 support so doesn't have a need for it anymore. The alternative was to add AlmaLinux 8.
> Drop EL7 & EL8 testing in CI

- .github/workflows/tests.yml
- .gitignore
- Makefile
- docs/admin/index.md
This creates a gitignore file to deal with generated files. The Makefile replaces the manual instructions and makes sure CI and user instructions are in sync. It even allows for parallel builds, even though the building is already super fast.
> Simplify build instructions by providing a Makefile
